name: checklist
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.6.1
  uuid: ^2.0.2
  rxdart: ^0.22.3
  provider: ^3.1.0
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: any
  flutter_coverage_badge: ^0.0.1+1

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/OpenSans-Regular.ttf
